import type { LocationItem } from '../types';

export const PRESET_LOCATIONS: LocationItem[] = [
  // ========== 杭州主城及西湖周边 ==========
  {
    id: 'hz_xihu',
    name: '杭州 · 西湖 (断桥/苏堤/三潭印月)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.24,
    longitude: 120.14,
    elevation: 10,
    keywords: ['西湖风景区', '断桥残雪', '苏堤春晓', '三潭印月', '白堤', '雷峰塔', '平湖秋月'],
    category: 'hangzhou',
  },
  {
    id: 'hz_xixi',
    name: '杭州 · 西溪湿地 (烟水渔庄/秋芦飞雪)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.27,
    longitude: 120.06,
    elevation: 8,
    keywords: ['西溪国家湿地公园', '烟水渔庄', '秋芦飞雪'],
    category: 'hangzhou',
  },
  {
    id: 'hz_lingyin',
    name: '杭州 · 灵隐寺 (飞来峰/冷泉)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.24,
    longitude: 120.10,
    elevation: 60,
    keywords: ['灵隐', '飞来峰', '天竺'],
    category: 'hangzhou',
  },
  {
    id: 'hz_liuheta',
    name: '杭州 · 六和塔 (钱塘江日落)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.20,
    longitude: 120.13,
    elevation: 80,
    keywords: ['六和塔', '钱塘江', '月轮山'],
    category: 'hangzhou',
  },
  {
    id: 'hz_qiantangchao',
    name: '海宁 · 钱塘江观潮 (盐官潮文化景区)',
    admin1: '浙江省',
    admin2: '嘉兴市海宁市',
    country: '中国',
    latitude: 30.39,
    longitude: 120.56,
    elevation: 6,
    keywords: ['钱塘江观潮', '盐官', '海宁潮'],
    category: 'hangzhou',
  },
  {
    id: 'hz_xianghu',
    name: '萧山 · 湘湖 (跨湖桥/城山)',
    admin1: '浙江省',
    admin2: '杭州市萧山区',
    country: '中国',
    latitude: 30.14,
    longitude: 120.22,
    elevation: 20,
    keywords: ['湘湖景区', '跨湖桥'],
    category: 'hangzhou',
  },
  {
    id: 'hz_chengshiyangtai',
    name: '杭州 · 钱江新城城市阳台 (钱塘江夜景)',
    admin1: '浙江省',
    admin2: '杭州市上城区',
    country: '中国',
    latitude: 30.24,
    longitude: 120.21,
    elevation: 15,
    keywords: ['城市阳台', '钱江新城', '波浪文化城'],
    category: 'hangzhou',
  },
  {
    id: 'hz_baoshishan',
    name: '杭州 · 宝石山 (保俶塔/西湖全景)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.26,
    longitude: 120.14,
    elevation: 200,
    category: 'hangzhou',
  },
  {
    id: 'hz_beigaofeng',
    name: '杭州 · 北高峰 (天下第一财神庙)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.25,
    longitude: 120.09,
    elevation: 314,
    category: 'hangzhou',
  },
  {
    id: 'hz_shililangdang',
    name: '杭州 · 十里琅珰 (龙井茶园晨曦)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.22,
    longitude: 120.11,
    elevation: 280,
    category: 'hangzhou',
  },
  {
    id: 'hz_banshan',
    name: '杭州 · 半山国家森林公园 (望宸阁)',
    admin1: '浙江省',
    admin2: '杭州市拱墅区',
    country: '中国',
    latitude: 30.36,
    longitude: 120.18,
    elevation: 284,
    category: 'hangzhou',
  },
  {
    id: 'hz_wuchaoshan',
    name: '杭州 · 午潮山 (城西第一峰/日落晨雾)',
    admin1: '浙江省',
    admin2: '杭州市余杭区',
    country: '中国',
    latitude: 30.17,
    longitude: 120.01,
    elevation: 495,
    category: 'hangzhou',
  },

  // ========== 杭州临安/富阳/桐庐/建德/淳安 ==========
  {
    id: 'la_taizijian',
    name: '临安 · 太子尖 (浙西三尖/日出云海绝顶)',
    admin1: '浙江省',
    admin2: '杭州市临安区',
    country: '中国',
    latitude: 30.13,
    longitude: 118.92,
    elevation: 1558,
    category: 'hangzhou',
  },
  {
    id: 'la_tianmushan',
    name: '临安 · 天目山 (仙人顶/壮丽云海大观)',
    admin1: '浙江省',
    admin2: '杭州市临安区',
    country: '中国',
    latitude: 30.34,
    longitude: 119.43,
    elevation: 1506,
    category: 'hangzhou',
  },
  {
    id: 'la_damingshan',
    name: '临安 · 大明山 (悬空栈道/万松峰云霞)',
    admin1: '浙江省',
    admin2: '杭州市临安区',
    country: '中国',
    latitude: 30.04,
    longitude: 119.00,
    elevation: 1489,
    category: 'hangzhou',
  },
  {
    id: 'fy_xingmeijian',
    name: '富阳 · 杏梅尖 (龙门山最高峰/富春江俯瞰)',
    admin1: '浙江省',
    admin2: '杭州市富阳区',
    country: '中国',
    latitude: 29.98,
    longitude: 119.95,
    elevation: 1067,
    category: 'hangzhou',
  },
  {
    id: 'tl_baiyunyuan',
    name: '桐庐 · 白云源 (富春江上游云深幽谷)',
    admin1: '浙江省',
    admin2: '杭州市桐庐县',
    country: '中国',
    latitude: 29.74,
    longitude: 119.64,
    elevation: 1000,
    category: 'hangzhou',
  },
  {
    id: 'ca_tianyushan',
    name: '千岛湖 · 天屿山 (群岛湖景绝美晚霞)',
    admin1: '浙江省',
    admin2: '杭州市淳安县',
    country: '中国',
    latitude: 29.62,
    longitude: 119.08,
    elevation: 320,
    category: 'hangzhou',
  },
  {
    id: 'jd_daciyan',
    name: '建德 · 大慈岩 (新安江白沙奇雾/悬空寺)',
    admin1: '浙江省',
    admin2: '杭州市建德市',
    country: '中国',
    latitude: 29.35,
    longitude: 119.26,
    elevation: 586,
    category: 'hangzhou',
  },

  // ========== 湖州安吉/德清莫干山 (杭州1小时圈) ==========
  {
    id: 'aj_tianchi',
    name: '安吉 · 江南天池 (高山天池/竹海云海日落)',
    admin1: '浙江省',
    admin2: '湖州市安吉县',
    country: '中国',
    latitude: 30.47,
    longitude: 119.58,
    elevation: 980,
    category: 'zhejiang',
  },
  {
    id: 'aj_yunshang',
    name: '安吉 · 云上草原 (悬崖高山草甸云浪)',
    admin1: '浙江省',
    admin2: '湖州市安吉县',
    country: '中国',
    latitude: 30.43,
    longitude: 119.65,
    elevation: 1168,
    category: 'zhejiang',
  },
  {
    id: 'dq_moganshan',
    name: '德清 · 莫干山 (旭光台日出/芦花荡晨雾)',
    admin1: '浙江省',
    admin2: '湖州市德清县',
    country: '中国',
    latitude: 30.60,
    longitude: 119.86,
    elevation: 750,
    category: 'zhejiang',
  },

  // ========== 绍兴/宁波/金华/台州/丽水 (浙江热门云海霞光) ==========
  {
    id: 'sz_fuzhishan',
    name: '嵊州 · 覆卮山 (千年梯田云海/万年石浪)',
    admin1: '浙江省',
    admin2: '绍兴市嵊州市',
    country: '中国',
    latitude: 29.76,
    longitude: 120.93,
    elevation: 861,
    category: 'zhejiang',
  },
  {
    id: 'xc_shijiufeng',
    name: '新昌 · 穿岩十九峰 (丹霞赤壁晨雾霞光)',
    admin1: '浙江省',
    admin2: '绍兴市新昌县',
    country: '中国',
    latitude: 29.41,
    longitude: 120.78,
    elevation: 400,
    category: 'zhejiang',
  },
  {
    id: 'yy_simingshan',
    name: '余姚 · 四明山 (四明山心观景台/水杉湿地)',
    admin1: '浙江省',
    admin2: '宁波市余姚市',
    country: '中国',
    latitude: 29.72,
    longitude: 121.08,
    elevation: 800,
    category: 'zhejiang',
  },
  {
    id: 'dy_dongbaishan',
    name: '东阳 · 东白山 (高山大风车/日出云海星空)',
    admin1: '浙江省',
    admin2: '金华市东阳市',
    country: '中国',
    latitude: 29.53,
    longitude: 120.44,
    elevation: 1194,
    category: 'zhejiang',
  },
  {
    id: 'tz_shenxianju',
    name: '台州 · 神仙居 (南天顶/如画奇峰云海)',
    admin1: '浙江省',
    admin2: '台州市仙居县',
    country: '中国',
    latitude: 28.69,
    longitude: 120.62,
    elevation: 880,
    category: 'zhejiang',
  },
  {
    id: 'tz_kuacangshan',
    name: '台州 · 括苍山 (浙东第一云海日出/风电场)',
    admin1: '浙江省',
    admin2: '台州市临海市',
    country: '中国',
    latitude: 28.80,
    longitude: 120.92,
    elevation: 1382,
    category: 'zhejiang',
  },
  {
    id: 'ls_nanjianyan',
    name: '丽水 · 遂昌南尖岩 (华东第一梯田云海)',
    admin1: '浙江省',
    admin2: '丽水市遂昌县',
    country: '中国',
    latitude: 28.52,
    longitude: 119.04,
    elevation: 1100,
    category: 'zhejiang',
  },
  {
    id: 'ls_xiandu',
    name: '丽水 · 缙云仙都 (鼎湖峰倒影晨雾仙气)',
    admin1: '浙江省',
    admin2: '丽水市缙云县',
    country: '中国',
    latitude: 28.74,
    longitude: 120.14,
    elevation: 300,
    category: 'zhejiang',
  },

  // ========== 全国经典参考 ==========
  {
    id: 'huangshan',
    name: '黄山风景区 (光明顶/始信峰)',
    admin1: '安徽省',
    admin2: '黄山市',
    country: '中国',
    latitude: 30.13,
    longitude: 118.17,
    elevation: 1864,
    category: 'national',
  },
  {
    id: 'wugongshan',
    name: '江西 · 武功山 (高山草甸金顶云海)',
    admin1: '江西省',
    admin2: '萍乡市',
    country: '中国',
    latitude: 27.42,
    longitude: 114.18,
    elevation: 1918,
    category: 'national',
  },
  {
    id: 'taishan',
    name: '山东 · 泰山 (日观峰/五岳之首)',
    admin1: '山东省',
    admin2: '泰安市',
    country: '中国',
    latitude: 36.25,
    longitude: 117.10,
    elevation: 1545,
    category: 'national',
  },
  {
    id: 'niubeishan',
    name: '四川 · 牛背山 (360°雪山云海观景台)',
    admin1: '四川省',
    admin2: '雅安市',
    country: '中国',
    latitude: 29.74,
    longitude: 102.32,
    elevation: 3660,
    category: 'national',
  },

  // ========== 杭州及近郊补充 ==========
  {
    id: 'hz_yuhuangshan',
    name: '杭州 · 玉皇山 (紫来洞/西湖钱塘江全景)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.22,
    longitude: 120.15,
    elevation: 237,
    keywords: ['玉皇飞云', '紫来洞', '八卦田'],
    category: 'hangzhou',
  },
  {
    id: 'hz_jiuyaoshan',
    name: '杭州 · 九曜山 (西湖日落观景台)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.23,
    longitude: 120.14,
    elevation: 198,
    keywords: ['九曜阁', '南高峰'],
    category: 'hangzhou',
  },
  {
    id: 'hz_lingshan',
    name: '杭州 · 灵山景区 (铜鉴湖/溶洞山景)',
    admin1: '浙江省',
    admin2: '杭州市西湖区',
    country: '中国',
    latitude: 30.10,
    longitude: 120.07,
    elevation: 260,
    keywords: ['灵山幻境', '铜鉴湖'],
    category: 'hangzhou',
  },
  {
    id: 'yh_jingshan',
    name: '余杭 · 径山 (径山寺/竹海云雾)',
    admin1: '浙江省',
    admin2: '杭州市余杭区',
    country: '中国',
    latitude: 30.38,
    longitude: 119.78,
    elevation: 769,
    keywords: ['径山寺', '径山古道'],
    category: 'hangzhou',
  },
  {
    id: 'yh_yaotoushan',
    name: '余杭 · 窑头山 (杭州北部最高峰)',
    admin1: '浙江省',
    admin2: '杭州市余杭区',
    country: '中国',
    latitude: 30.48,
    longitude: 119.73,
    elevation: 1095,
    keywords: ['鸬鸟山', '山沟沟'],
    category: 'hangzhou',
  },
  {
    id: 'la_qingliangfeng',
    name: '临安 · 清凉峰 (浙西自然保护区)',
    admin1: '浙江省',
    admin2: '杭州市临安区',
    country: '中国',
    latitude: 30.11,
    longitude: 118.86,
    elevation: 1787,
    keywords: ['清凉峰保护区', '浙西最高峰'],
    category: 'hangzhou',
  },
  {
    id: 'la_longtangshan',
    name: '临安 · 龙塘山 (高山湿地/日出云海)',
    admin1: '浙江省',
    admin2: '杭州市临安区',
    country: '中国',
    latitude: 30.18,
    longitude: 118.89,
    elevation: 1586,
    keywords: ['龙塘山自然保护区'],
    category: 'hangzhou',
  },
  {
    id: 'chun_qiandaohu_meifeng',
    name: '千岛湖 · 梅峰岛 (群岛全景)',
    admin1: '浙江省',
    admin2: '杭州市淳安县',
    country: '中国',
    latitude: 29.58,
    longitude: 118.92,
    elevation: 300,
    keywords: ['梅峰观岛', '千岛湖观景台'],
    category: 'hangzhou',
  },
  {
    id: 'tl_daqishan',
    name: '桐庐 · 大奇山 (富春江山水)',
    admin1: '浙江省',
    admin2: '杭州市桐庐县',
    country: '中国',
    latitude: 29.76,
    longitude: 119.70,
    elevation: 600,
    keywords: ['大奇山国家森林公园'],
    category: 'hangzhou',
  },
  {
    id: 'jd_sanjiangkou',
    name: '建德 · 三江口 (严州古城/江雾)',
    admin1: '浙江省',
    admin2: '杭州市建德市',
    country: '中国',
    latitude: 29.47,
    longitude: 119.28,
    elevation: 120,
    keywords: ['梅城古镇', '新安江', '富春江'],
    category: 'hangzhou',
  },

  // ========== 浙江省内补充 ==========
  {
    id: 'wz_yandangshan',
    name: '温州 · 雁荡山 (灵峰/百岗尖)',
    admin1: '浙江省',
    admin2: '温州市乐清市',
    country: '中国',
    latitude: 28.37,
    longitude: 121.06,
    elevation: 1108,
    keywords: ['北雁荡山', '百岗尖', '灵峰'],
    category: 'zhejiang',
  },
  {
    id: 'wz_nanjidanao',
    name: '温州 · 南麂岛 (大沙岙海上日出)',
    admin1: '浙江省',
    admin2: '温州市平阳县',
    country: '中国',
    latitude: 27.46,
    longitude: 121.05,
    elevation: 230,
    keywords: ['南麂列岛', '大沙岙', '海岛日出'],
    category: 'zhejiang',
  },
  {
    id: 'wz_daluoshan',
    name: '温州 · 大罗山 (龙脊/天河水库)',
    admin1: '浙江省',
    admin2: '温州市瓯海区',
    country: '中国',
    latitude: 27.91,
    longitude: 120.73,
    elevation: 707,
    keywords: ['龙脊', '天河水库'],
    category: 'zhejiang',
  },
  {
    id: 'tz_tiantai',
    name: '台州 · 天台山 (华顶云锦杜鹃)',
    admin1: '浙江省',
    admin2: '台州市天台县',
    country: '中国',
    latitude: 29.25,
    longitude: 121.05,
    elevation: 1098,
    keywords: ['华顶山', '石梁飞瀑'],
    category: 'zhejiang',
  },
  {
    id: 'tz_dachen',
    name: '台州 · 大陈岛 (甲午岩海上日出)',
    admin1: '浙江省',
    admin2: '台州市椒江区',
    country: '中国',
    latitude: 28.45,
    longitude: 121.89,
    elevation: 200,
    keywords: ['甲午岩', '下大陈岛'],
    category: 'zhejiang',
  },
  {
    id: 'nb_xuedoushan',
    name: '宁波 · 雪窦山 (妙高台/千丈岩)',
    admin1: '浙江省',
    admin2: '宁波市奉化区',
    country: '中国',
    latitude: 29.69,
    longitude: 121.22,
    elevation: 800,
    keywords: ['溪口雪窦山', '妙高台'],
    category: 'zhejiang',
  },
  {
    id: 'nb_songlanshan',
    name: '宁波 · 松兰山 (东海日出)',
    admin1: '浙江省',
    admin2: '宁波市象山县',
    country: '中国',
    latitude: 29.49,
    longitude: 121.93,
    elevation: 80,
    keywords: ['松兰山海滨', '象山海岸'],
    category: 'zhejiang',
  },
  {
    id: 'zs_putuoshan',
    name: '舟山 · 普陀山 (佛顶山/东海日出)',
    admin1: '浙江省',
    admin2: '舟山市普陀区',
    country: '中国',
    latitude: 30.01,
    longitude: 122.39,
    elevation: 291,
    keywords: ['佛顶山', '慧济寺'],
    category: 'zhejiang',
  },
  {
    id: 'zs_dongjidao',
    name: '舟山 · 东极岛 (新世纪第一缕曙光)',
    admin1: '浙江省',
    admin2: '舟山市普陀区',
    country: '中国',
    latitude: 30.19,
    longitude: 122.68,
    elevation: 150,
    keywords: ['东福山岛', '庙子湖岛', '海上日出'],
    category: 'zhejiang',
  },
  {
    id: 'zs_huaniaodao',
    name: '舟山 · 花鸟岛 (灯塔/海上日落)',
    admin1: '浙江省',
    admin2: '舟山市嵊泗县',
    country: '中国',
    latitude: 30.86,
    longitude: 122.67,
    elevation: 236,
    keywords: ['花鸟灯塔', '嵊泗列岛'],
    category: 'zhejiang',
  },
  {
    id: 'jh_fangyan',
    name: '金华 · 方岩 (丹霞孤峰)',
    admin1: '浙江省',
    admin2: '金华市永康市',
    country: '中国',
    latitude: 28.93,
    longitude: 120.22,
    elevation: 384,
    keywords: ['方岩风景区', '南岩'],
    category: 'zhejiang',
  },
  {
    id: 'jh_dapanshan',
    name: '金华 · 大盘山 (高山草甸/云海)',
    admin1: '浙江省',
    admin2: '金华市磐安县',
    country: '中国',
    latitude: 28.98,
    longitude: 120.53,
    elevation: 1274,
    keywords: ['大盘山自然保护区'],
    category: 'zhejiang',
  },
  {
    id: 'qz_jianglangshan',
    name: '衢州 · 江郎山 (三爿石丹霞)',
    admin1: '浙江省',
    admin2: '衢州市江山市',
    country: '中国',
    latitude: 28.53,
    longitude: 118.56,
    elevation: 824,
    keywords: ['三爿石', '江郎山世界遗产'],
    category: 'zhejiang',
  },
  {
    id: 'qz_qianjiangyuan',
    name: '衢州 · 钱江源 (莲花尖/原始森林)',
    admin1: '浙江省',
    admin2: '衢州市开化县',
    country: '中国',
    latitude: 29.42,
    longitude: 118.19,
    elevation: 1145,
    keywords: ['钱江源国家公园', '莲花尖'],
    category: 'zhejiang',
  },
  {
    id: 'ls_baishanzu',
    name: '丽水 · 百山祖 (浙江第二高峰)',
    admin1: '浙江省',
    admin2: '丽水市庆元县',
    country: '中国',
    latitude: 27.76,
    longitude: 119.20,
    elevation: 1856,
    keywords: ['百山祖国家公园'],
    category: 'zhejiang',
  },
  {
    id: 'ls_huangmaojian',
    name: '丽水 · 黄茅尖 (浙江最高峰)',
    admin1: '浙江省',
    admin2: '丽水市龙泉市',
    country: '中国',
    latitude: 27.89,
    longitude: 119.18,
    elevation: 1929,
    keywords: ['凤阳山', '浙江之巅'],
    category: 'zhejiang',
  },
  {
    id: 'ls_yunhetitian',
    name: '丽水 · 云和梯田 (九曲云环日出)',
    admin1: '浙江省',
    admin2: '丽水市云和县',
    country: '中国',
    latitude: 28.05,
    longitude: 119.48,
    elevation: 800,
    keywords: ['九曲云环', '白银谷'],
    category: 'zhejiang',
  },

  // ========== 上海、江苏、安徽、江西、福建 ==========
  {
    id: 'sh_sheshan',
    name: '上海 · 佘山 (上海陆地最高点)',
    admin1: '上海市',
    admin2: '松江区',
    country: '中国',
    latitude: 31.10,
    longitude: 121.19,
    elevation: 101,
    keywords: ['西佘山', '佘山天文台'],
    category: 'zhejiang',
  },
  {
    id: 'js_zijinshan',
    name: '南京 · 紫金山 (头陀岭日出)',
    admin1: '江苏省',
    admin2: '南京市玄武区',
    country: '中国',
    latitude: 32.07,
    longitude: 118.85,
    elevation: 449,
    keywords: ['钟山', '头陀岭'],
    category: 'zhejiang',
  },
  {
    id: 'js_lingshan',
    name: '无锡 · 灵山 (太湖山水)',
    admin1: '江苏省',
    admin2: '无锡市滨湖区',
    country: '中国',
    latitude: 31.42,
    longitude: 120.09,
    elevation: 150,
    keywords: ['灵山胜境', '马山'],
    category: 'zhejiang',
  },
  {
    id: 'js_huaguoshan',
    name: '连云港 · 花果山 (玉女峰/海上云台)',
    admin1: '江苏省',
    admin2: '连云港市海州区',
    country: '中国',
    latitude: 34.64,
    longitude: 119.27,
    elevation: 625,
    keywords: ['玉女峰', '云台山'],
    category: 'zhejiang',
  },
  {
    id: 'ah_jiuhuashan',
    name: '安徽 · 九华山 (十王峰/花台)',
    admin1: '安徽省',
    admin2: '池州市青阳县',
    country: '中国',
    latitude: 30.48,
    longitude: 117.81,
    elevation: 1344,
    keywords: ['十王峰', '花台', '天台峰'],
    category: 'zhejiang',
  },
  {
    id: 'ah_tianzhushan',
    name: '安徽 · 天柱山 (天柱峰/云海)',
    admin1: '安徽省',
    admin2: '安庆市潜山市',
    country: '中国',
    latitude: 30.73,
    longitude: 116.46,
    elevation: 1489,
    keywords: ['天柱峰', '皖山'],
    category: 'zhejiang',
  },
  {
    id: 'ah_qiyunshan',
    name: '安徽 · 齐云山 (丹霞云海)',
    admin1: '安徽省',
    admin2: '黄山市休宁县',
    country: '中国',
    latitude: 29.81,
    longitude: 118.03,
    elevation: 585,
    keywords: ['白岳', '月华街'],
    category: 'zhejiang',
  },
  {
    id: 'ah_tiantangzhai',
    name: '安徽 · 天堂寨 (大别山主峰)',
    admin1: '安徽省',
    admin2: '六安市金寨县',
    country: '中国',
    latitude: 31.13,
    longitude: 115.78,
    elevation: 1729,
    keywords: ['大别山', '白马大峡谷'],
    category: 'zhejiang',
  },
  {
    id: 'jx_lushan',
    name: '江西 · 庐山 (含鄱口/五老峰)',
    admin1: '江西省',
    admin2: '九江市庐山市',
    country: '中国',
    latitude: 29.57,
    longitude: 115.97,
    elevation: 1474,
    keywords: ['五老峰', '含鄱口', '汉阳峰'],
    category: 'zhejiang',
  },
  {
    id: 'jx_sanqingshan',
    name: '江西 · 三清山 (玉京峰/东方女神)',
    admin1: '江西省',
    admin2: '上饶市玉山县',
    country: '中国',
    latitude: 28.91,
    longitude: 118.07,
    elevation: 1819,
    keywords: ['玉京峰', '东方女神'],
    category: 'zhejiang',
  },
  {
    id: 'jx_mingyueshan',
    name: '江西 · 明月山 (青云栈道/日出)',
    admin1: '江西省',
    admin2: '宜春市袁州区',
    country: '中国',
    latitude: 27.59,
    longitude: 114.28,
    elevation: 1736,
    keywords: ['青云栈道', '太平山'],
    category: 'zhejiang',
  },
  {
    id: 'fj_wuyishan',
    name: '福建 · 武夷山 (天游峰/九曲溪)',
    admin1: '福建省',
    admin2: '南平市武夷山市',
    country: '中国',
    latitude: 27.66,
    longitude: 117.96,
    elevation: 408,
    keywords: ['天游峰', '九曲溪', '大王峰'],
    category: 'zhejiang',
  },
  {
    id: 'fj_taimushan',
    name: '福建 · 太姥山 (山海云雾)',
    admin1: '福建省',
    admin2: '宁德市福鼎市',
    country: '中国',
    latitude: 27.12,
    longitude: 120.19,
    elevation: 917,
    keywords: ['太姥峰', '夫妻峰'],
    category: 'zhejiang',
  },
  {
    id: 'fj_xiapu',
    name: '福建 · 霞浦 (花竹日出/滩涂光影)',
    admin1: '福建省',
    admin2: '宁德市霞浦县',
    country: '中国',
    latitude: 26.74,
    longitude: 120.17,
    elevation: 180,
    keywords: ['花竹村', '北岐滩涂', '东壁日落'],
    category: 'zhejiang',
  },
  {
    id: 'fj_pingtan',
    name: '福建 · 平潭岛 (长江澳海上日落)',
    admin1: '福建省',
    admin2: '福州市平潭县',
    country: '中国',
    latitude: 25.58,
    longitude: 119.78,
    elevation: 120,
    keywords: ['长江澳', '北部生态廊道', '蓝眼泪'],
    category: 'zhejiang',
  },

  // ========== 全国经典户外观景地补充 ==========
  {
    id: 'huashan',
    name: '陕西 · 华山 (东峰日出/长空栈道)',
    admin1: '陕西省',
    admin2: '渭南市华阴市',
    country: '中国',
    latitude: 34.48,
    longitude: 110.09,
    elevation: 2155,
    keywords: ['西岳', '东峰', '南峰', '长空栈道'],
    category: 'national',
  },
  {
    id: 'songshan',
    name: '河南 · 嵩山 (峻极峰/太室山)',
    admin1: '河南省',
    admin2: '郑州市登封市',
    country: '中国',
    latitude: 34.49,
    longitude: 112.96,
    elevation: 1492,
    keywords: ['中岳', '峻极峰', '太室山'],
    category: 'national',
  },
  {
    id: 'hengshan_north',
    name: '山西 · 恒山 (天峰岭)',
    admin1: '山西省',
    admin2: '大同市浑源县',
    country: '中国',
    latitude: 39.67,
    longitude: 113.74,
    elevation: 2017,
    keywords: ['北岳', '天峰岭', '悬空寺'],
    category: 'national',
  },
  {
    id: 'hengshan_south',
    name: '湖南 · 衡山 (祝融峰日出)',
    admin1: '湖南省',
    admin2: '衡阳市南岳区',
    country: '中国',
    latitude: 27.25,
    longitude: 112.66,
    elevation: 1300,
    keywords: ['南岳', '祝融峰'],
    category: 'national',
  },
  {
    id: 'wutaishan',
    name: '山西 · 五台山 (东台望海峰)',
    admin1: '山西省',
    admin2: '忻州市五台县',
    country: '中国',
    latitude: 39.07,
    longitude: 113.60,
    elevation: 3061,
    keywords: ['东台顶', '望海峰', '北台叶斗峰'],
    category: 'national',
  },
  {
    id: 'emeishan',
    name: '四川 · 峨眉山 (金顶日出云海)',
    admin1: '四川省',
    admin2: '乐山市峨眉山市',
    country: '中国',
    latitude: 29.52,
    longitude: 103.34,
    elevation: 3079,
    keywords: ['金顶', '普贤菩萨', '云海佛光'],
    category: 'national',
  },
  {
    id: 'siguniangshan',
    name: '四川 · 四姑娘山 (猫鼻梁观景台)',
    admin1: '四川省',
    admin2: '阿坝州小金县',
    country: '中国',
    latitude: 31.11,
    longitude: 102.87,
    elevation: 3500,
    keywords: ['猫鼻梁', '幺妹峰', '双桥沟'],
    category: 'national',
  },
  {
    id: 'gonggashan_zimeiyakou',
    name: '四川 · 贡嘎山 (子梅垭口观景点)',
    admin1: '四川省',
    admin2: '甘孜州康定市',
    country: '中国',
    latitude: 29.61,
    longitude: 101.85,
    elevation: 4550,
    keywords: ['蜀山之王', '子梅垭口', '贡嘎雪山'],
    category: 'national',
  },
  {
    id: 'yading',
    name: '四川 · 稻城亚丁 (洛绒牛场/三神山)',
    admin1: '四川省',
    admin2: '甘孜州稻城县',
    country: '中国',
    latitude: 28.44,
    longitude: 100.31,
    elevation: 4180,
    keywords: ['仙乃日', '央迈勇', '夏诺多吉', '洛绒牛场'],
    category: 'national',
  },
  {
    id: 'yulongxueshan',
    name: '云南 · 玉龙雪山 (甘海子/冰川公园)',
    admin1: '云南省',
    admin2: '丽江市玉龙县',
    country: '中国',
    latitude: 27.10,
    longitude: 100.18,
    elevation: 4506,
    keywords: ['扇子陡', '甘海子', '冰川公园'],
    category: 'national',
  },
  {
    id: 'meilixueshan',
    name: '云南 · 梅里雪山 (飞来寺日照金山)',
    admin1: '云南省',
    admin2: '迪庆州德钦县',
    country: '中国',
    latitude: 28.44,
    longitude: 98.88,
    elevation: 3450,
    keywords: ['飞来寺', '卡瓦格博', '日照金山'],
    category: 'national',
  },
  {
    id: 'cangshan',
    name: '云南 · 苍山 (洗马潭/洱海全景)',
    admin1: '云南省',
    admin2: '大理州大理市',
    country: '中国',
    latitude: 25.66,
    longitude: 100.10,
    elevation: 3920,
    keywords: ['洗马潭', '点苍山', '洱海'],
    category: 'national',
  },
  {
    id: 'fanjingshan',
    name: '贵州 · 梵净山 (红云金顶)',
    admin1: '贵州省',
    admin2: '铜仁市江口县',
    country: '中国',
    latitude: 27.91,
    longitude: 108.70,
    elevation: 2572,
    keywords: ['红云金顶', '蘑菇石'],
    category: 'national',
  },
  {
    id: 'zhangjiajie',
    name: '湖南 · 张家界 (天子山/袁家界)',
    admin1: '湖南省',
    admin2: '张家界市武陵源区',
    country: '中国',
    latitude: 29.35,
    longitude: 110.48,
    elevation: 1262,
    keywords: ['武陵源', '天子山', '袁家界'],
    category: 'national',
  },
  {
    id: 'changbaishan',
    name: '吉林 · 长白山 (天池观景台)',
    admin1: '吉林省',
    admin2: '延边州安图县',
    country: '中国',
    latitude: 42.01,
    longitude: 128.06,
    elevation: 2189,
    keywords: ['长白山天池', '白头山'],
    category: 'national',
  },
  {
    id: 'wudalianchi',
    name: '黑龙江 · 五大连池 (老黑山火山群)',
    admin1: '黑龙江省',
    admin2: '黑河市五大连池市',
    country: '中国',
    latitude: 48.66,
    longitude: 126.13,
    elevation: 516,
    keywords: ['老黑山', '火山群'],
    category: 'national',
  },
  {
    id: 'hulunbuir',
    name: '内蒙古 · 呼伦贝尔草原 (莫日格勒河)',
    admin1: '内蒙古自治区',
    admin2: '呼伦贝尔市陈巴尔虎旗',
    country: '中国',
    latitude: 49.49,
    longitude: 119.77,
    elevation: 650,
    keywords: ['莫日格勒河', '天下第一曲水'],
    category: 'national',
  },
  {
    id: 'kanas',
    name: '新疆 · 喀纳斯 (观鱼台/神仙湾晨雾)',
    admin1: '新疆维吾尔自治区',
    admin2: '阿勒泰地区布尔津县',
    country: '中国',
    latitude: 48.70,
    longitude: 87.01,
    elevation: 2030,
    keywords: ['观鱼台', '神仙湾', '月亮湾'],
    category: 'national',
  },
  {
    id: 'sayramlake',
    name: '新疆 · 赛里木湖 (环湖日出星空)',
    admin1: '新疆维吾尔自治区',
    admin2: '博尔塔拉州博乐市',
    country: '中国',
    latitude: 44.59,
    longitude: 81.17,
    elevation: 2073,
    keywords: ['大西洋最后一滴眼泪', '赛湖'],
    category: 'national',
  },
  {
    id: 'qinghailake',
    name: '青海 · 青海湖 (黑马河日出)',
    admin1: '青海省',
    admin2: '海南州共和县',
    country: '中国',
    latitude: 36.73,
    longitude: 99.78,
    elevation: 3196,
    keywords: ['黑马河', '二郎剑', '青海湖日出'],
    category: 'national',
  },
  {
    id: 'qilianshan',
    name: '青海 · 祁连山 (卓尔山观景台)',
    admin1: '青海省',
    admin2: '海北州祁连县',
    country: '中国',
    latitude: 38.20,
    longitude: 100.24,
    elevation: 3100,
    keywords: ['卓尔山', '牛心山'],
    category: 'national',
  },
  {
    id: 'mingshashan',
    name: '甘肃 · 鸣沙山 (月牙泉日落)',
    admin1: '甘肃省',
    admin2: '酒泉市敦煌市',
    country: '中国',
    latitude: 40.09,
    longitude: 94.67,
    elevation: 1340,
    keywords: ['月牙泉', '敦煌日落'],
    category: 'national',
  },
  {
    id: 'helanshan',
    name: '宁夏 · 贺兰山 (滚钟口/星空)',
    admin1: '宁夏回族自治区',
    admin2: '银川市西夏区',
    country: '中国',
    latitude: 38.72,
    longitude: 105.93,
    elevation: 2100,
    keywords: ['滚钟口', '苏峪口'],
    category: 'national',
  },
  {
    id: 'wuzhishan',
    name: '海南 · 五指山 (海南屋脊)',
    admin1: '海南省',
    admin2: '五指山市',
    country: '中国',
    latitude: 18.90,
    longitude: 109.68,
    elevation: 1867,
    keywords: ['海南第一峰', '热带雨林'],
    category: 'national',
  },

  // ========== 浙江经典水乡、湖泊与古城 ==========
  {
    id: 'jx_wuzhen',
    name: '桐乡 · 乌镇 (西栅夜景/水乡晨雾)',
    admin1: '浙江省',
    admin2: '嘉兴市桐乡市',
    country: '中国',
    latitude: 30.74,
    longitude: 120.49,
    elevation: 6,
    keywords: ['乌镇西栅', '乌镇东栅', '江南水乡'],
    category: 'zhejiang',
  },
  {
    id: 'jx_xitang',
    name: '嘉善 · 西塘 (烟雨长廊)',
    admin1: '浙江省',
    admin2: '嘉兴市嘉善县',
    country: '中国',
    latitude: 30.94,
    longitude: 120.89,
    elevation: 5,
    keywords: ['西塘古镇', '烟雨长廊'],
    category: 'zhejiang',
  },
  {
    id: 'hz_nanxun',
    name: '湖州 · 南浔古镇 (小莲庄/嘉业堂)',
    admin1: '浙江省',
    admin2: '湖州市南浔区',
    country: '中国',
    latitude: 30.87,
    longitude: 120.43,
    elevation: 5,
    keywords: ['南浔', '小莲庄'],
    category: 'zhejiang',
  },
  {
    id: 'jx_nanhu',
    name: '嘉兴 · 南湖 (湖心岛烟雨楼)',
    admin1: '浙江省',
    admin2: '嘉兴市南湖区',
    country: '中国',
    latitude: 30.76,
    longitude: 120.76,
    elevation: 5,
    keywords: ['嘉兴南湖', '烟雨楼'],
    category: 'zhejiang',
  },
  {
    id: 'nb_dongqianhu',
    name: '宁波 · 东钱湖 (陶公山日落)',
    admin1: '浙江省',
    admin2: '宁波市鄞州区',
    country: '中国',
    latitude: 29.77,
    longitude: 121.63,
    elevation: 10,
    keywords: ['东钱湖', '陶公山'],
    category: 'zhejiang',
  },
  {
    id: 'wz_nanxijiang',
    name: '永嘉 · 楠溪江 (岩头古村/狮子岩)',
    admin1: '浙江省',
    admin2: '温州市永嘉县',
    country: '中国',
    latitude: 28.29,
    longitude: 120.70,
    elevation: 40,
    keywords: ['楠溪江', '岩头', '苍坡村'],
    category: 'zhejiang',
  },
  {
    id: 'wz_jiangxinyu',
    name: '温州 · 江心屿 (双塔对峙/瓯江日落)',
    admin1: '浙江省',
    admin2: '温州市鹿城区',
    country: '中国',
    latitude: 28.03,
    longitude: 120.64,
    elevation: 8,
    keywords: ['江心屿', '瓯江'],
    category: 'zhejiang',
  },
  {
    id: 'sx_keyan',
    name: '绍兴 · 柯岩 (云骨/鉴湖)',
    admin1: '浙江省',
    admin2: '绍兴市柯桥区',
    country: '中国',
    latitude: 30.05,
    longitude: 120.48,
    elevation: 40,
    keywords: ['柯岩风景区', '鉴湖'],
    category: 'zhejiang',
  },
  {
    id: 'sx_donghu',
    name: '绍兴 · 东湖 (陶公洞/石壁倒影)',
    admin1: '浙江省',
    admin2: '绍兴市越城区',
    country: '中国',
    latitude: 29.99,
    longitude: 120.62,
    elevation: 15,
    keywords: ['绍兴东湖'],
    category: 'zhejiang',
  },

  // ========== 沪苏皖赣闽湖景与城市观景点 ==========
  {
    id: 'sh_waitan',
    name: '上海 · 外滩 (黄浦江天际线)',
    admin1: '上海市',
    admin2: '黄浦区',
    country: '中国',
    latitude: 31.24,
    longitude: 121.49,
    elevation: 6,
    keywords: ['外滩', '黄浦江', '万国建筑'],
    category: 'zhejiang',
  },
  {
    id: 'js_shouxihu',
    name: '扬州 · 瘦西湖 (二十四桥/五亭桥)',
    admin1: '江苏省',
    admin2: '扬州市邗江区',
    country: '中国',
    latitude: 32.41,
    longitude: 119.42,
    elevation: 8,
    keywords: ['瘦西湖', '二十四桥'],
    category: 'zhejiang',
  },
  {
    id: 'js_xuanwuhu',
    name: '南京 · 玄武湖 (环洲/台城晚霞)',
    admin1: '江苏省',
    admin2: '南京市玄武区',
    country: '中国',
    latitude: 32.07,
    longitude: 118.80,
    elevation: 12,
    keywords: ['玄武湖', '台城'],
    category: 'zhejiang',
  },
  {
    id: 'js_taihu',
    name: '无锡 · 太湖鼋头渚 (充山隐秀/湖光)',
    admin1: '江苏省',
    admin2: '无锡市滨湖区',
    country: '中国',
    latitude: 31.52,
    longitude: 120.22,
    elevation: 20,
    keywords: ['鼋头渚', '太湖', '鼋渚春涛'],
    category: 'zhejiang',
  },
  {
    id: 'js_zhouzhuang',
    name: '苏州 · 周庄 (双桥/水乡晨雾)',
    admin1: '江苏省',
    admin2: '苏州市昆山市',
    country: '中国',
    latitude: 31.11,
    longitude: 120.85,
    elevation: 5,
    keywords: ['周庄古镇', '双桥'],
    category: 'zhejiang',
  },
  {
    id: 'ah_hongcun',
    name: '黟县 · 宏村 (月沼/南湖倒影)',
    admin1: '安徽省',
    admin2: '黄山市黟县',
    country: '中国',
    latitude: 29.99,
    longitude: 117.99,
    elevation: 300,
    keywords: ['宏村', '月沼', '南湖'],
    category: 'zhejiang',
  },

  // ========== 全国经典湖景、古城与城市观景点 ==========
  {
    id: 'bj_badaling',
    name: '北京 · 八达岭长城 (北八楼日落)',
    admin1: '北京市',
    admin2: '延庆区',
    country: '中国',
    latitude: 40.36,
    longitude: 116.02,
    elevation: 1015,
    keywords: ['八达岭', '长城', '北八楼'],
    category: 'national',
  },
  {
    id: 'bj_yiheyuan',
    name: '北京 · 颐和园 (佛香阁/昆明湖日落)',
    admin1: '北京市',
    admin2: '海淀区',
    country: '中国',
    latitude: 39.99,
    longitude: 116.27,
    elevation: 60,
    keywords: ['颐和园', '昆明湖', '佛香阁'],
    category: 'national',
  },
  {
    id: 'bj_xiangshan',
    name: '北京 · 香山 (鬼见愁/红叶)',
    admin1: '北京市',
    admin2: '海淀区',
    country: '中国',
    latitude: 39.99,
    longitude: 116.19,
    elevation: 557,
    keywords: ['香山公园', '香炉峰', '红叶'],
    category: 'national',
  },
  {
    id: 'gx_lijiang',
    name: '桂林 · 漓江 (杨堤兴坪/九马画山)',
    admin1: '广西壮族自治区',
    admin2: '桂林市阳朔县',
    country: '中国',
    latitude: 24.78,
    longitude: 110.50,
    elevation: 140,
    keywords: ['漓江', '兴坪', '九马画山', '桂林山水'],
    category: 'national',
  },
  {
    id: 'gx_yangshuo',
    name: '阳朔 · 遇龙河 (十里画廊/西街)',
    admin1: '广西壮族自治区',
    admin2: '桂林市阳朔县',
    country: '中国',
    latitude: 24.78,
    longitude: 110.48,
    elevation: 130,
    keywords: ['遇龙河', '阳朔西街', '十里画廊'],
    category: 'national',
  },
  {
    id: 'sc_jiuzhaigou',
    name: '四川 · 九寨沟 (五花海/长海)',
    admin1: '四川省',
    admin2: '阿坝州九寨沟县',
    country: '中国',
    latitude: 33.17,
    longitude: 103.92,
    elevation: 3100,
    keywords: ['九寨沟', '五花海', '诺日朗'],
    category: 'national',
  },
  {
    id: 'sc_huanglong',
    name: '四川 · 黄龙 (五彩池钙华)',
    admin1: '四川省',
    admin2: '阿坝州松潘县',
    country: '中国',
    latitude: 32.74,
    longitude: 103.83,
    elevation: 3600,
    keywords: ['黄龙沟', '五彩池'],
    category: 'national',
  },
  {
    id: 'yn_erhai',
    name: '大理 · 洱海 (苍山洱海/喜洲日落)',
    admin1: '云南省',
    admin2: '大理州大理市',
    country: '中国',
    latitude: 25.76,
    longitude: 100.19,
    elevation: 1972,
    keywords: ['洱海', '喜洲', '双廊', '才村码头'],
    category: 'national',
  },
  {
    id: 'yn_luguhu',
    name: '云南 · 泸沽湖 (里格半岛晨雾)',
    admin1: '云南省',
    admin2: '丽江市宁蒗县',
    country: '中国',
    latitude: 27.70,
    longitude: 100.78,
    elevation: 2690,
    keywords: ['泸沽湖', '里格', '草海'],
    category: 'national',
  },
  {
    id: 'yn_dianchi',
    name: '昆明 · 滇池 (西山龙门俯瞰)',
    admin1: '云南省',
    admin2: '昆明市西山区',
    country: '中国',
    latitude: 24.96,
    longitude: 102.65,
    elevation: 1886,
    keywords: ['滇池', '西山龙门', '海埂大坝'],
    category: 'national',
  },
  {
    id: 'fj_gulangyu',
    name: '厦门 · 鼓浪屿 (日光岩/菽庄花园)',
    admin1: '福建省',
    admin2: '厦门市思明区',
    country: '中国',
    latitude: 24.45,
    longitude: 118.07,
    elevation: 30,
    keywords: ['鼓浪屿', '日光岩', '钢琴博物馆'],
    category: 'national',
  },
  {
    id: 'gz_huangguoshu',
    name: '贵州 · 黄果树瀑布 (大瀑布观景台)',
    admin1: '贵州省',
    admin2: '安顺市镇宁县',
    country: '中国',
    latitude: 25.99,
    longitude: 105.67,
    elevation: 900,
    keywords: ['黄果树', '大瀑布'],
    category: 'national',
  },
  {
    id: 'xz_namucuo',
    name: '西藏 · 纳木错 (圣象天门/湖岸日出)',
    admin1: '西藏自治区',
    admin2: '拉萨市当雄县',
    country: '中国',
    latitude: 30.72,
    longitude: 90.60,
    elevation: 4718,
    keywords: ['纳木错', '圣象天门'],
    category: 'national',
  },
  {
    id: 'xz_potala',
    name: '拉萨 · 布达拉宫 (红山日落金顶)',
    admin1: '西藏自治区',
    admin2: '拉萨市城关区',
    country: '中国',
    latitude: 29.66,
    longitude: 91.12,
    elevation: 3700,
    keywords: ['布达拉宫', '红山'],
    category: 'national',
  },
  {
    id: 'sd_laoshan',
    name: '青岛 · 崂山 (巨峰/海上名山)',
    admin1: '山东省',
    admin2: '青岛市崂山区',
    country: '中国',
    latitude: 36.19,
    longitude: 120.62,
    elevation: 1133,
    keywords: ['崂山', '巨峰', '仰口'],
    category: 'national',
  },
  {
    id: 'hb_wudangshan',
    name: '湖北 · 武当山 (金顶/南岩)',
    admin1: '湖北省',
    admin2: '十堰市丹江口市',
    country: '中国',
    latitude: 32.40,
    longitude: 111.00,
    elevation: 1612,
    keywords: ['武当山', '金顶', '南岩宫'],
    category: 'national',
  },
];

/** Search every bundled location, independent of the currently selected category. */
export function searchPresetLocations(query: string): LocationItem[] {
  return searchLocationsIn(PRESET_LOCATIONS, query);
}

export function isSameLocation(a: LocationItem, b: LocationItem): boolean {
  return (
    a.id === b.id ||
    (Math.abs(a.latitude - b.latitude) < 0.01 && Math.abs(a.longitude - b.longitude) < 0.01)
  );
}

function searchLocationsIn(list: LocationItem[], query: string): LocationItem[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  return list.filter((location) => {
    const searchable = [
      location.name,
      location.admin1,
      location.admin2,
      location.country,
      ...(location.keywords || []),
    ]
      .filter(Boolean)
      .join(' ')
      .toLowerCase();
    return searchable.indexOf(normalized) !== -1;
  });
}

function dedupeLocations(list: LocationItem[]): LocationItem[] {
  const unique: LocationItem[] = [];
  list.forEach((item) => {
    if (!unique.some((kept) => isSameLocation(kept, item))) {
      unique.push(item);
    }
  });
  return unique;
}

/** Search presets plus cached map / saved places. History hits stay in front. */
export function searchOfflineLocations(
  query: string,
  extras: LocationItem[] = []
): LocationItem[] {
  return dedupeLocations(searchLocationsIn(extras, query).concat(searchPresetLocations(query)));
}

export const MAX_MAP_HISTORY = 30;

export function upsertMapHistory(
  list: LocationItem[],
  loc: LocationItem,
  max = MAX_MAP_HISTORY
): LocationItem[] {
  const existing = list.find((item) => isSameLocation(item, loc));
  const stored: LocationItem = {
    ...loc,
    id: existing?.id || loc.id,
    isCustom: true,
    category: 'custom',
  };
  return [stored, ...list.filter((item) => !isSameLocation(item, loc))].slice(0, max);
}

const STORAGE_SAVED_LOCATIONS_KEY = 'sky_forecast_saved_locations';
const STORAGE_CURRENT_LOCATION_KEY = 'sky_forecast_current_location';
const STORAGE_MAP_HISTORY_KEY = 'sky_forecast_map_history';

function readStoredLocations(key: string): LocationItem[] {
  try {
    const raw = wx.getStorageSync(key);
    if (!raw) return [];
    return typeof raw === 'string' ? JSON.parse(raw) : raw;
  } catch {
    return [];
  }
}

export function getMapHistory(): LocationItem[] {
  return readStoredLocations(STORAGE_MAP_HISTORY_KEY);
}

export function rememberMapLocation(loc: LocationItem): LocationItem {
  const next = upsertMapHistory(getMapHistory(), loc);
  try {
    wx.setStorageSync(STORAGE_MAP_HISTORY_KEY, next);
  } catch (err) {
    console.warn('Failed to remember map location', err);
  }
  return next[0];
}

export function getSavedLocations(): LocationItem[] {
  return readStoredLocations(STORAGE_SAVED_LOCATIONS_KEY);
}

export function saveLocation(loc: LocationItem): void {
  try {
    const list = getSavedLocations();
    const existsIndex = list.findIndex((x) => isSameLocation(x, loc));
    if (existsIndex >= 0) {
      list[existsIndex] = { ...loc, id: list[existsIndex].id };
    } else {
      list.unshift(loc);
    }
    wx.setStorageSync(STORAGE_SAVED_LOCATIONS_KEY, list);
  } catch (err) {
    console.warn('Failed to save location', err);
  }
}

export function removeSavedLocation(id: string): void {
  try {
    const list = getSavedLocations().filter((x) => x.id !== id);
    wx.setStorageSync(STORAGE_SAVED_LOCATIONS_KEY, list);
  } catch (err) {
    console.warn('Failed to remove location', err);
  }
}

export function getLastActiveLocation(): LocationItem {
  try {
    const raw = wx.getStorageSync(STORAGE_CURRENT_LOCATION_KEY);
    if (raw) {
      const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw;
      if (parsed && parsed.latitude && parsed.longitude) {
        return parsed;
      }
    }
  } catch {
    // fallback
  }
  return PRESET_LOCATIONS[0]; // Default to 杭州宝石山
}

export function setLastActiveLocation(loc: LocationItem): void {
  try {
    wx.setStorageSync(STORAGE_CURRENT_LOCATION_KEY, loc);
  } catch (err) {
    console.warn('Failed to store active location', err);
  }
}
